name: 'NPM Publish'
on:
  workflow_dispatch:
    inputs:
      version:
        description: npm version
        required: true
env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/.yarn/unplugged

jobs:
  job_install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Compute dependency cache key
        id: compute_lockfile_hash
        run: echo "hash=${{ hashFiles('yarn.lock') }}" >> $GITHUB_OUTPUT

      - name: Check dependency cache
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_lockfile_hash }}

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: yarn
    outputs:
      dependency_cache_key: ${{ steps.compute_lockfile_hash.outputs.hash }}

  job_build_deploy:
    name: Build + npm publish
    needs: job_install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: main

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build plugin
        run: yarn build:prod
